### ISSUE TITLE
Need more iconic logo

### ISSUE THREAD

**Issue by dsernst** [liquidvote/join#3]
I've been re-using this logo since beginning of the crowdocracy org:

![crowdocracy](https://cloud.githubusercontent.com/assets/6340841/18045791/9bd24572-6da2-11e6-9b92-8348518d8bc1.png)

But think we can do much better.

Any ideas?

**Comment by dsernst** [comment]
- should work better in black & white, and at a smaller size
- should be uniquely memorable

**Comment by dsernst** [comment]
visual inspirations: [democracy](https://www.google.com/search?q=democracy&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiD0q2JnebOAhWD8x4KHYulDw8Q_AUICSgC&biw=1268&bih=898), [vote](https://www.google.com/search?q=democracy&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiD0q2JnebOAhWD8x4KHYulDw8Q_AUICSgC&biw=1268&bih=898#tbm=isch&q=vote), [liquid democracy](https://www.google.com/search?q=democracy&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiD0q2JnebOAhWD8x4KHYulDw8Q_AUICSgC&biw=1268&bih=898#tbm=isch&q=liquid+democracy)

I like the liquid-looking [american flag from Macklemore's Can't Hold Us video](https://www.google.com/search?q=macklemore+can%27t+hold+us+flag&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjL3P7JnebOAhWMmx4KHfQ8B28Q_AUICSgC&biw=840&bih=898) (came to the video after reading this interesting article [NYT: The Great Affluence Society](http://www.nytimes.com/2016/08/09/opinion/the-great-affluence-fallacy.html)):
![the heist USA flag](http://i.imgur.com/TqmeZZY.jpg)

this spiral image ([source](https://bitcoinclassic.consider.it/integrate-delegative-democracy-into-the-voting-process)): 
![spiral photo](https://d2rtgkroh5y135.cloudfront.net/system/avatars/613324/large/The_Super_Spirals2_wallpaper.jpg)

this interesting multi-legged arrow symbol for diverse opinions coming together:
![multi-legged arrow](http://1.bp.blogspot.com/-ekgO-PrfueY/T19hGVw2JFI/AAAAAAAABW4/m6KFbSndcxc/s1600/vote%2Bit.jpg)

This interlocking-rings direct democracy symbol ([source](http://www.firstworldvote.org/Direct%20Democracy.html)):
![direct democracy 3 circles](http://www.firstworldvote.org/images/direct-democracy.png)

**Comment by dsernst** [comment]
Interesting symbols here: https://thenounproject.com/search/?q=vote

my favorites from that page: 
- https://thenounproject.com/search/?q=vote&i=2783 white checkmark on black circle
- https://thenounproject.com/search/?q=vote&i=441275 facebook-ish thumbs up
- https://thenounproject.com/search/?q=vote&i=584798 plus on upward label
- https://thenounproject.com/search/?q=vote&i=28302 cartoonish check in front of box outline
- https://thenounproject.com/search/?q=vote&i=38332 checkmark made out of lots of individual dots
- https://thenounproject.com/search/?q=vote&i=331215 3 dimensional checkmark
- https://thenounproject.com/search/?q=vote&i=318695 black check with circle outline
- https://thenounproject.com/search/?q=vote&i=333362 check overlaid on circle in stylish way
- https://thenounproject.com/search/?q=vote&i=176588 check with circle sketches around it

There are lot of checkmark variations because there are a lot of interesting ways of presenting it. Not because I necessarily think it's the right way to go.

**Comment by dsernst** [comment]
Right now I'm still feeling like a more abstract symbol could be more powerful, and really liked the 3-interlocking circles design.

**Comment by dsernst** [comment]
Having fun trying to adopt the 3-rings icon for USA colors:

![three-rings-icon](https://cloud.githubusercontent.com/assets/6340841/18048655/654c2748-6db1-11e6-85d0-fba6479862e4.png)

**Comment by dsernst** [comment]
I shared this red-white-and-blue 3 circles icon with a few people yesterday. Here are some of the comments:

> democracy looks a little squished for some reason
> I don't love it but I can't put my finger on why. Is there a reason for the three circles?
> When I reopened it I liked it more. I think that it should be more true red and blue
> I like the idea of it being a water droplet or something 
> In the red white and blue colors 
> But I see what you're going for 
> It's definitely a great start!
> I would shift the colors all 90 degrees
> Blue on top red on right and white on the left for the existing mark up

and they included these sketches:

![ld water drop sketch](https://cloud.githubusercontent.com/assets/6340841/18105480/62fdd3b6-6eb4-11e6-8f45-3d31f61bfb1e.jpg)

------------------

> I like the logo. The young woman sitting next to me in the plane who is on her way back to LA likes it too

--------------

> Great logo! Why the colors in that order? I couldn't tell at first it was supposed to be red-white-and-blue. What about red on left, white on top, blue on right?

**Comment by rjatkinson2** [comment]
Worked with David on sketchifying the logo. We used a bit of a hacky approach to build the transitions, so I'd recommend ultimately using geometric circles for all parts of the implementation in the future to ensure congruency. There's work left on lining up all the vectors perfectly and ensuring proper nesting of borders. Nonetheless, see attached for the current sketch mock.

[liquiddemocracy.sketch.zip](https://github.com/liquidvote/join/files/478493/liquiddemocracy.sketch.zip)

**Comment by dsernst** [comment]
I made a few more minor tweaks. Here's a screenshot of the latest, the grey bg is just for illustration:

<img width="246" alt="icon transparent bg" src="https://cloud.githubusercontent.com/assets/6340841/18613015/ae3b8954-7d23-11e6-8094-80abbae21fc8.png">

And the latest Sketch file:
[icon.sketch.zip](https://github.com/liquidvote/join/files/478531/icon.sketch.zip)

**Comment by dsernst** [comment]
![icon-with-text small](https://cloud.githubusercontent.com/assets/6340841/18614136/c6ddf2ac-7d3d-11e6-8aa9-7118fe862dba.png)

moved white-to-blue transition behind red-to-white

([icon.sketch.zip](https://github.com/liquidvote/join/files/478592/icon.sketch.zip))

**Comment by jaredscheib** [comment]
Really love this. Thanks, Ryan!

I'd go with the white-to-blue overlap one, as the red seems to create
fragmentation, whereas the first one feels integrated/unified, plus it
emphasis purity into liquid. Red is a bit more burner-friendly, but then we
should definitely go with Smelting Democracy ;)

**Comment by rjatkinson2** [comment]
I agree with Jared, although good to see the different variations. Also note, with the three overlapping "S" turns in the middle, the lowest layer only shows a small triangle (the rest is covered up). In the second design, the tiny triangle is in the lower left position making the logo asymmetric.

One additional thought - given that this is largely borrowed from the Irish counterpart, it would be best to obtain permission if we haven't done so already.

**Comment by dsernst** [comment]
Good points all around. I've sent the Irish organization an email.

**Comment by jaredscheib** [comment]
:thumbs-up-rainbow:

**Comment by dsernst** [comment]
I'm gonna close this for now. Thanks again, @rjatkinson2 👍
