### ISSUE TITLE
Email confimation text may be outdated

### ISSUE THREAD

**Issue by dsernst** [liquidvote/join#6]
@jaredscheib Can you fill this out http://join.liquid.vote and check the auto-responder email text?

- [x] It's no longer in sync with the changes we made the other day to the form introduction.
- [x] It makes a bunch of references to Liquid Democracy Party that have been removed from the form.

**Comment by jaredscheib** [comment]
When I fill it out, I get:
""
Signup for Liquid Democracy
Thank you, please share this with your friends and family.
""

Seems like you may have edited it?

At any rate, I would suggest something like:
""
Thank you for joining us
Please share https://liquid.vote, and learn more at http://demo.liquid.vote.
We will keep you informed and engaged as we build out our Liquid Democracy.
""

**Comment by dsernst** [comment]
Is that the email that comes after?

**Comment by jaredscheib** [comment]
Ah, whoops.

I get:
""
Hi Jared Scheib,

This confirms that you registered for the Liquid Democracy Party, via https://join.liquid.vote . You don't need to do anything else for now. You'll be included for major announcements, such as when the first version of the Liquid Democracy app is available.

In the meantime, you're invited to come say hi in our chatroom and share links about Liquid Democracy with your friends and family:

The Liquid Democracy Party exists to bring delegative democracy to the United States. It upgrades government to better match voters' preferences and removes the need for corruptible elected legislators. It does this all without requiring more effort for the voter than our current representative system.

Learn more here: http://liquid.vote

Thank you!
""

I'll review now.

**Comment by jaredscheib** [comment]
How about:
""
Hi Jared Scheib,

This confirms that you signed up to stay tuned about Liquid Democracy, via https://join.liquid.vote. We'll keep you in the loop on opportunities to get involved, as well as major announcements, like our upcoming alpha release of the Liquid Democracy app.

In the meantime, we invite your voice in our ongoing conversation at https://gitter.im/Crowdocracy/thedap (** SHALL WE CHANGE THIS NOW ?).

Liquid Democracy promises to empower our most trustworthy leaders, give us true choice and accountability, and transform our politics and society. We are building the open-source Liquid Democracy Party to bring this powerful evolution of democracy to the United States. We're excited to have you be a part of our movement.

Learn more at http://liquid.vote/learn-more  (**LINK TO INDEX OF RESOURCES liquid.vote/learn-more ?)..

Thank you,
David Ernst, Jared Scheib, & Rohan Dixit
""

**Comment by dsernst** [comment]
👍 👍 I've changed the email to:

>
Hi `recipientName`,
>
This confirms your registration to stay tuned about Liquid Democracy, via http://join.liquid.vote . Thank you.
>
We'll keep you in the loop about major announcements, such as when the first version of the Liquid Democracy app is available.
>
For now, you're invited to come say hi in <a href='https://gitter.im/Crowdocracy/thedap'>our chatroom</a> and share links about Liquid Democracy with your friends and family:
>
*Liquid Democracy promises to empower our most trustworthy leaders, give us true choice and accountability, and transform our politics and society. It does this all without requiring more effort for the voter than our current representative system.*
>
Learn more at http://liquid.vote
>
Thanks!

-------------------

- Yesterday I sent in a request to Gitter's support to rename the chatroom URL. Haven't heard back yet. (See https://github.com/liquidvote/org/issues/6)
- What is this http://liquid.vote/learn-more you propose? See https://github.com/liquidvote/org/issues/5 for dedicated issue about that domain.

Right now, this email message is configured through Google Apps Scripts, which is pretty powerful and free. There are a lot of language gotcha's though (it looks like JavaScript but it's not), terrible revision control, and poor alerting system, which all makes it very brittle. So I'm weary about opening up more access to its underlying code. When we get an initial API up, we can move this over to a normal open-source piece of infrastructure, so it can be inspected and updated with PRs.
